Add docker login mapping
buildkite/migration pull request #46
Opened 2023-10-23 06:21 UTC by jradtilbrook

2023-10-23 14:21 UTC, toote requested changes
If we are going to start translating actions, I believe they should be part of [the corresponding step translation](https://github.com/buildkite/migration/blob/main/app/lib/bk/compat/parsers/gha/steps.rb#L34-L36) to avoid the comments about it being unsupported

2023-10-24 02:28 UTC, jradtilbrook commented
Sweet thanks @mcncl. Just need to run `UPDATE_SNAPSHOTS=true bundle exec rspec`

2023-10-24 02:30 UTC, jradtilbrook commented
> Sweet thanks @mcncl. Just need to run `UPDATE_SNAPSHOTS=true bundle exec rspec`

Done

2023-10-24 02:38 UTC, mcncl approved these changes

2023-10-24 02:45 UTC, merged