SUP-1874 - `approval` jobs -> block steps and conditionals
buildkite/migration pull request #84
Opened 2024-02-29 23:20 UTC by james2791

Some tweaking to the `BlockStep` class (`approval` translation) with the inclusion of a `conditional` attribute to handle the setting of pipelines that only have one workflow.

Previously if you defined something like this:

```
... jobs ...

workflows:
  stage_test_approve_deploy:
    when:
      equal: [ true, RELEASE_STAGING ]
    jobs:
      - build-and-package
      - gate:
          type: approval
          requires:
            - build-and-package
      - publish
```

The `BlockStep` never had a `conditional` attribute, and failed to parse for these cases. Now added; with the potential of setting it via model definition - we loop through each step and [assign](https://github.com/buildkite/migration/blob/main/app/lib/bk/compat/parsers/circleci.rb#L82) the first conditional to each `CircleCIStep` via Circle's `when` definition through `simplify_group`

2024-03-04 18:09 UTC, toote requested changes
Great fix! Though I would re-work the examples to be more independent from each other. As the comments state, have one to test the approval step and merge the other one into the `conditions.yml` instead as it is actually meant to test conditionals

2024-03-04 18:09 UTC, toote commented on app/spec/lib/bk/compat/circleci/examples/approval-with-conditions.yml
Maybe it would be a good idea to make the approval job condition part of the `conditions.yml` example instead of mixing it up with approvals unnecessarily.

2024-03-05 01:30 UTC, james2791 commented on app/lib/bk/compat/pipeline/step.rb
> -
One I missed - thanks @toote 😅

2024-03-05 01:33 UTC, james2791 commented on app/spec/lib/bk/compat/circleci/examples/approval-with-conditions.yml
> +        - equal: [ true, RELEASE_STAGING ]
👍

2024-03-05 01:40 UTC, james2791 commented on app/spec/lib/bk/compat/circleci/examples/approval-with-conditions.yml
> +      - publish
👀 - tweaking this with the merge over to `conditions.yml` 👍

2024-03-05 01:48 UTC, james2791 commented on app/spec/lib/bk/compat/circleci/examples/approval-with-conditions.yml
This exactly 👍 - Ive since moved it across

2024-03-07 02:39 UTC, james2791 commented on app/lib/bk/compat/pipeline/step.rb
> +          h[:if] = @conditional unless @conditional.nil?
Added 👍

2024-03-07 02:40 UTC, james2791 commented on app/spec/lib/bk/compat/circleci/examples/conditions.yml
> +      equal: [ "main", BUILDKITE_BRANCH ]
Not sure how I didnt notice this - adjusted to the GHA param!

2024-03-07 02:42 UTC, merged